INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_STEVES_AMPLITUDE_MODULATION steves_amplitude_modulation)

FIND_PATH(
    STEVES_AMPLITUDE_MODULATION_INCLUDE_DIRS
    NAMES steves_amplitude_modulation/api.h
    HINTS $ENV{STEVES_AMPLITUDE_MODULATION_DIR}/include
        ${PC_STEVES_AMPLITUDE_MODULATION_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    STEVES_AMPLITUDE_MODULATION_LIBRARIES
    NAMES gnuradio-steves_amplitude_modulation
    HINTS $ENV{STEVES_AMPLITUDE_MODULATION_DIR}/lib
        ${PC_STEVES_AMPLITUDE_MODULATION_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/steves_amplitude_modulationTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(STEVES_AMPLITUDE_MODULATION DEFAULT_MSG STEVES_AMPLITUDE_MODULATION_LIBRARIES STEVES_AMPLITUDE_MODULATION_INCLUDE_DIRS)
MARK_AS_ADVANCED(STEVES_AMPLITUDE_MODULATION_LIBRARIES STEVES_AMPLITUDE_MODULATION_INCLUDE_DIRS)
